### ISSUE TITLE
Add Accessibility through keyboard to the sidebar like Devdocs.io

### ISSUE THREAD

**Issue by blazeeboy** [blazeeboy/devtools#10]
SideBar should handle keyboard arrow (up and down) to select list items, and enter to open the selected tool, just like [Devdocs.io](http://www.devdocs.io)

**Comment by AmrEldib** [comment]
[ember-keyboard-shortcuts](https://github.com/Skalar/ember-keyboard-shortcuts)

**Comment by blazeeboy** [comment]
looks suitable for the job, i'll try it

**Comment by blazeeboy** [comment]
Thanks @AmrEldib it worked perfectly.
