### ISSUE TITLE
Strings Manipulation

### ISSUE THREAD

**Issue by MohamedBassem** [blazeeboy/devtools#14]
Hi Emad,
I like the idea of the tool very much. Thank you.
One of the functionalities that I need very often is the strings manipulation things.
For example:
- Getting the length of a certain string.
- Generating a random string with some criteria ( lower/upper case, numbers .. ).
- Reversing a string ( Although not very useful, if fits in the strings manipulation section ).

If you think that this would be something useful, I can implement and pull request it. If you have any other things in mind concerning strings, please share it with me.

P.S. After posting this, "Strings manipulation" doesn't seem to be the correct title for this issue :smile:

**Comment by blazeeboy** [comment]
Great Idea mohamed, 
i think you idea could be implemented in a different way.

1. length of string should be added to the textarea, any input textarea in DevTools uses `devtools-textarea` component, we add common features to this component, so adding a number to the right bottom or right top section indicating the current string length will be great.

2. generating random string with some criteria looks like `password generator` feature, so ew can create it as a separate tool with that name providing such feature, and i would be more that happy to help you code it.

3. reversing a string doesn't look like it will be very useful, so can we discard this point?

Thanks for providing such ideas it'll make DevTools even better, let me know what'd you think of the above suggestions.

**Comment by MohamedBassem** [comment]
@blazeeboy Thanks :smile: 

1. Your idea seems better, I've pull requested it for you :smile:
2. Makes sense, I can implement and pull request it later if you want.
3. Since now we won't have any strings sections then yes, we can just discard it.

**Comment by blazeeboy** [comment]
Hello @MohamedBassem , should i expect a password generator tool for this issue?

**Comment by MohamedBassem** [comment]
Hi Emad, Well let's close this and open another one for the password generator. I'm currently having my semester final exams, If someone claimed it before I finish then he can do it, otherwise I will :+1:

**Comment by blazeeboy** [comment]
Cool
