### ISSUE TITLE
Choose License

### ISSUE THREAD

**Issue by AmrEldib** [blazeeboy/devtools#18]
[Tool to help choose an OSS license](http://choosealicense.com/)

**Comment by blazeeboy** [comment]
Do you think adding tools to sidebar and opening it as iframe would be a good step? or we should stick to the current approach?

**Comment by AmrEldib** [comment]
I think we should stick with the current approach. I think the goal of this project is more than just making a collection of tools, you can do that with a static page of links. The goal is to make those tools better by integrating them into one collection and offering better user experience.
It's important to give credit to the original author of those tools, and you're already doing that.
It's also important to pick a license that doesn't violate the license of those other tools, or pick tools with permissive licenses.
