### ISSUE TITLE
App Doesn't Load

### ISSUE THREAD

**Issue by AmrEldib** [blazeeboy/devtools#26]
Application doesn't load at all, it's just a blank page. Console error is as follows:
In Firefox Nightly (Today's)
`None of the "sha512" hashes in the integrity attribute match the content of the subresource.`
In Chrome 47.0.2526.106 m
`Failed to find a valid digest in the 'integrity' attribute for resource 'http://www.blazeboy.me/devtools/assets/devtools-dbd1b6be46db16eb5d3270d709c9174b.js' with computed SHA-256 integrity '2qXoHfZSfB9ceWJu5I1MjnrRdLXs89gKSjAcT6MtPJ0='. The resource has been blocked.`
Side note: I think it would be useful to test the deployment with clear cache or private browser mode.

**Comment by blazeeboy** [comment]
will investigate noe

**Comment by AmrEldib** [comment]
There's another error in the console, but it's not related
`The resource at "http://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled.[Learn More] devtools`
I have 'Do Not Track' turned on

**Comment by blazeeboy** [comment]
aha it's irrelevant

**Comment by MohamedBassem** [comment]
I'm also currently facing this issue.

**Comment by AmrEldib** [comment]
It's not fixed for me either. Tried clearing the cache, private mode, and different browser. Still there on Firefox and Chrome.

**Comment by MohamedBassem** [comment]
This maybe relevant : https://github.com/ember-cli/ember-cli/issues/5040

**Comment by blazeeboy** [comment]
Weird, it's loading correctly on my firefox, i'll investigate further

**Comment by blazeeboy** [comment]
@AmrEldib @MohamedBassem can we check if this solved the bug?

**Comment by MohamedBassem** [comment]
It did, but seems like this is a temporary fix, if you found the commit that introduced this thing maybe we can find a better way to fix it

**Comment by blazeeboy** [comment]
Sure, i'll dig nore after finishing this tool #25

**Comment by MohamedBassem** [comment]
Cool, good luck!

**Comment by AmrEldib** [comment]
Seems resolved now. Thanks!

**Comment by blazeeboy** [comment]
Ok, the ember-cli main developer said that adding `integrity` to script tags is the solution not a work around, it's just ember-cli blueprint didn't add it by default and the new versions will.

**Comment by jonathanKingston** [comment]
@blazeeboy was the integrity failing on the testem script out of interest? (just seen this)

**Comment by blazeeboy** [comment]
I didn't get that error, neither when running tests not the app itself, but @AmrEldib had it on firefox with the main app.
couldn't regenerate the issue on my machine.

**Comment by AmrEldib** [comment]
I found the problem while trying to use the app. You can find a description of the error above.
