### ISSUE TITLE
Drawer Button Doesn't Respond to Touch Event

### ISSUE THREAD

**Issue by AmrEldib** [blazeeboy/devtools#27]
Low priority. If you load the site on mobile (not exactly a common usage scenario, I know), the side panel takes most of the screen. Touching the drawer button brings up a tooltip but doesn't hide the menu.
However, if you use the responsive design mode in Firefox, the menu works fine. I'm guessing it responds to mouse events but not touch.
I've tested using Firefox on desktop and Android.

**Comment by blazeeboy** [comment]
Humm, I think there are 2 issues in here : 

* Side menu should be hidden by default on mobile
* Side menu button (and god knows what other buttons) should respond to touch events

the app over all should be tested on mobile.
I have a concern, should we really support mobile?

**Comment by AmrEldib** [comment]
'should we support mobile' is an important question. I think the answer is (as usual) it depends.
If you can support mobile by doing very little work, then why not?
The app is already responsive and looks great on mobile. You get that for almost no work at all. Maybe mobile support is only one or two steps away.

**Comment by blazeeboy** [comment]
ok, let's work on it.

**Comment by AmrEldib** [comment]
Maybe [this](http://stackoverflow.com/questions/12385574/onclick-event-in-a-link-with-zurb-foundation-tooltip-on-touch-device) is the problem. Tooltop for the drawer icon handles the touch/click event of the container [list item](https://github.com/blazeeboy/devtools/blob/master/app/templates/components/app-navbar.hbs#L3).
This prevents the child link from responding to the click event.
Foundation has a way of prevent tooltips on mobile. See the [Disable for touch events](http://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html) section. Maybe that will fix it?

**Comment by blazeeboy** [comment]
I can't regenerate the bug on my phone, would you please test it?, i moved the click/touch action to the parent `li` and removed tooltip on mobile

**Comment by AmrEldib** [comment]
Yup, it's working now. Thanks dude!
