### ISSUE TITLE
Add Together.js for collaboration

### ISSUE THREAD

**Issue by blazeeboy** [blazeeboy/devtools#5]
Study the visibility of adding [together.js](https://togetherjs.com/) to enable collaboration between any tool user.

if the tool doesn't need any backend from our side then we'll add it to the system.

**Comment by AmrEldib** [comment]
Check out [ShareDrop](https://github.com/cowbell/sharedrop)
It's an Ember app

**Comment by blazeeboy** [comment]
aha, this could be included somehow as a tool, it can't replace together.js as together aims to have a collaboration inside the page like chat/live editing, in a tool like HTML/CSS/JS sandbox it'll help as a coaching mode.
we can add ShareDrop as a Feature to be added as a tool i guess.
