### ISSUE TITLE
custom Ember textarea component that accepts dropping files

### ISSUE THREAD

**Issue by blazeeboy** [blazeeboy/devtools#8]
the normal textarea doesn't accept drag-n-drop, a custom textarea component should be created to be shared among all tools.

the textarea should have the same interface currently ember has in addition to the following features : 

* when a user drag a file over it it should show an indicator that he can drop the file here
* when user drops the file it should read it and fill the textarea with its contents if possible
* add clipboard actions as a toolbar copy-cut-paste
* select all icon to select all textarea contents

the first design suggestion is to enhance the current ember textarea component with the required features.
another design is to create a separate component `devtools-textarea` with the same interface in addition to the required features.

**Comment by AmrEldib** [comment]
Maybe it should also have "Select All", "Copy" and "Paste".
This will be helpful in tools like minify and encoding tools.

**Comment by blazeeboy** [comment]
i modified the original issue to include clipboard actions and select all action.
