### ISSUE TITLE
Ember should use #! instead of html5 push feature

### ISSUE THREAD

**Issue by blazeeboy** [blazeeboy/devtools#9]
# Scenario 

1. open devtools 
2. choose a tool and open it
3. copy the url and send it to a friend
4. user opens the url
5. github pages complain that the page doesn't exists

# Cause

ember use HTML5 history push by default so auto prefix tool for example has the url `http://www.blazeboy.me/devtools/autoprefixer`, github can't redirect user the index.html and can't be configured to do so.

# Solution 

We should use the #! notation instead so the autoprefixer tools should has `http://www.blazeboy.me/devtools/index.html#!autoprefixer` instead of `http://www.blazeboy.me/devtools/autoprefixer` 
also the whole app should has a switch in environment files to fix/ignore fix.

**Comment by AmrEldib** [comment]
I wonder if you can use 404 page to redirect to index.html/<route> 
Read [here](http://stackoverflow.com/a/30017545/463)

**Comment by blazeeboy** [comment]
interesting, i didn't know that workaround, yes i think it could work.
https://help.github.com/articles/custom-404-pages/
https://github.com/lionello/lionello.github.io/commit/c175f6524a53e29aea1890c8a758afd0e8944852

**Comment by blazeeboy** [comment]
it didn't work, github can't find urls such as `index.html/autoprefixer` i think we'll need to fallback to the previously suggested workaround, using #! instead, any other ideas we can try?

**Comment by blazeeboy** [comment]
it turns out that this is a simple configuration key in the environment :D
